# Generated by Django 3.2.8 on 2021-10-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="For user role choice. Two choices possible:            'sale' or 'support'", max_length=10, null=True, verbose_name='User role')),
            ],
            options={
                'verbose_name_plural': 'User roles',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(help_text="Each user is related to a role. This role will attribute            user to a group with permissions. Roles are 'sale' or 'support'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomUsers', to='accounts.userrole', verbose_name='role'),
        ),
    ]
