# Generated by Django 3.2.8 on 2021-10-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211031_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(help_text="Each user is related to a role. This role will attribute            user to a group with permissions. Roles are 'sale' or 'support'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='accounts.userrole', verbose_name='role'),
        ),
    ]
