# Generated by Django 3.2.8 on 2021-11-01 08:13

from django.db import migrations


def create_groups(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    view_customer = Permission.objects.get(codename='view_customer')
    view_contract = Permission.objects.get(codename='view_contract')
    view_event = Permission.objects.get(codename='view_event')

    add_customer = Permission.objects.get(codename='add_customer')
    add_contract = Permission.objects.get(codename='add_contract')
    add_event = Permission.objects.get(codename='add_event')

    change_customer = Permission.objects.get(codename='change_customer')
    change_contract = Permission.objects.get(codename='change_contract')
    change_event = Permission.objects.get(codename='change_event')

    sale_permissions = [
        view_customer,
        view_contract,
        view_event,
        add_customer,
        add_contract,
        add_event,
        change_customer,
        change_contract,
    ]

    support_permissions = [
        view_customer,
        view_contract,
        view_event,
        change_event,
    ]

    sale = Group(name='sale')
    sale.save()
    sale.permissions.set(sale_permissions)

    support = Group(name='support')
    support.save()
    support.permissions.set(support_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
