# Generated by Django 3.2.8 on 2021-11-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211101_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='', help_text="Each user is related to a role. This role will attribute            user to a group with permissions. Roles are 'sale' or 'support'", max_length=20, null=True, verbose_name='role'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
