# Generated by Django 3.2.8 on 2021-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Each client has a first name with max 25 caracters.', max_length=25, verbose_name='client first name')),
                ('last_name', models.CharField(help_text='Each client has a last name with max 25 caracters.', max_length=25, verbose_name='client last name')),
                ('email', models.EmailField(help_text='Each client has an email with max 100 caracters.', max_length=100, verbose_name='client email')),
                ('phone', models.CharField(blank=True, help_text='Each client has a phone number with max 20 caracters.', max_length=20, verbose_name='client phone number')),
                ('mobile', models.CharField(help_text='Each client has a mobile phone number with max 20             caracters.', max_length=20, verbose_name='client mobile phone number')),
                ('company_name', models.CharField(blank=True, help_text='Company name client for professional clients with max             250 caracters.', max_length=250, verbose_name='client company name')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='client creation date is automatically filled in.', verbose_name='created datetime client case')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
