# Generated by Django 3.2.8 on 2021-10-30 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, help_text='client update datetime is automatically filled in.', verbose_name='updated datetime client case'),
        ),
        migrations.AddField(
            model_name='client',
            name='sales_customuser',
            field=models.ForeignKey(default=1, help_text='The admin team asign a salesperson to each client.            this seller negotiates with the client for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.customuser', verbose_name='sales contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='client creation datetime is automatically filled in.', verbose_name='created datetime client case'),
        ),
    ]
