# Generated by Django 3.2.9 on 2021-11-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='support_customuser',
            field=models.ForeignKey(blank=True, help_text='The admin team asign a support person to each customer.            this supprt personn manage event oàrganisation with the customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Contact support'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_customuser',
            field=models.ForeignKey(blank=True, help_text='The admin team asign a salesperson to each customer.            this seller negotiates with the customer for contracts sign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumers', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(help_text='Each contract is related to a customer', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_customer', to='CRM.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_customuser',
            field=models.ForeignKey(help_text='The admin team asign a salesperson to each customer.            this seller negotiates with the customer for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
    ]
