# Generated by Django 3.2.8 on 2021-10-30 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0002_auto_20211030_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Custumer',
        ),
    ]
