# Generated by Django 3.2.9 on 2021-11-22 08:41

from django.db import migrations


def create_status_event(apps, schema_editor):
    """Status event creation in database
    1: En préparation
    2: En cours
    3: Terminé
    """
    Status = apps.get_model('CRM', 'EventStatus')

    prepa = Status(status='En Préparation')
    prepa.save()

    progress = Status(status='En cours')
    progress.save()

    ended = Status(status='Terminé')
    ended.save()


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_status_event),
    ]
