# Generated by Django 3.2.8 on 2021-10-30 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0003_rename_client_custumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name custumer for professional custumers with max             250 caracters.', max_length=250, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='custumer creation datetime is automatically filled in.', verbose_name='Date création client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, help_text='custumer update datetime is automatically filled in.', verbose_name='Date mise à jour client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='email',
            field=models.EmailField(help_text='Each custumer has an email with max 100 caracters.', max_length=100, verbose_name='email client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='first_name',
            field=models.CharField(help_text='Each custumer has a first name with max 25 caracters.', max_length=25, verbose_name='Prénom client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='last_name',
            field=models.CharField(help_text='Each custumer has a last name with max 25 caracters.', max_length=25, verbose_name='Nom de famille client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='mobile',
            field=models.CharField(help_text='Each custumer has a mobile phone number with max 20             caracters.', max_length=20, verbose_name='Téléphone mobile client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='phone',
            field=models.CharField(blank=True, help_text='Each custumer has a phone number with max 20 caracters.', max_length=20, verbose_name='Téléphone fixe client'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='sales_customuser',
            field=models.ForeignKey(help_text='The admin team asign a salesperson to each custumer.            this seller negotiates with the custumer for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='custumers', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='contract creation datetime is automatically filled in.', verbose_name='Date création client')),
                ('datetime_updated', models.DateTimeField(auto_now=True, help_text='contract update datetime is automatically filled in.', verbose_name='Date mise à jour client')),
                ('status_sign', models.BooleanField(default=False, help_text='Has to pass on True when contract is signed', verbose_name='Signature contrat')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Contract amount when signed. Float number', max_digits=9, verbose_name='Montant du contrat')),
                ('payment_due', models.DateField(help_text='Payment due. Format:  AAAA-MM-JJ', verbose_name='Echéance de paiement')),
                ('custumer', models.ForeignKey(help_text='Each contract is related to a custumer', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_custumer', to='CRM.custumer', verbose_name='client')),
                ('sales_customuser', models.ForeignKey(help_text='The admin team asign a salesperson to each custumer.            this seller negotiates with the custumer for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur')),
            ],
            options={
                'ordering': ['custumer', '-datetime_created'],
            },
        ),
    ]
