# Generated by Django 3.2.8 on 2021-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20211030_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='contract creation datetime is automatically filled in.', verbose_name='Date création contrat'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, help_text='contract update datetime is automatically filled in.', verbose_name='Date mise à jour contrat'),
        ),
    ]
