# Generated by Django 3.2.8 on 2021-10-31 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0005_auto_20211030_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['customer', '-datetime_created']},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='custumer',
            new_name='customer',
        ),
    ]
