# Generated by Django 3.2.8 on 2021-10-31 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0006_auto_20211031_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text="Pour choix du statut de l'évènement. Contient trois choix            possibels: En préparation, En cours, Terminé", max_length=250, verbose_name='Status évènement')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(help_text='Each contract is related to a customer', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_custumer', to='CRM.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(help_text='Payment due. Format: AAAA-MM-JJ', verbose_name='Echéance de paiement'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_customuser',
            field=models.ForeignKey(help_text='The admin team asign a salesperson to each customer.            this seller negotiates with the customer for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name customer for professional customers with            max 250 caracters.', max_length=250, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Each customer has an email with max 100 caracters.', max_length=100, verbose_name='email client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='Each customer has a first name with max 25 caracters.', max_length=25, verbose_name='Prénom client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Each customer has a last name with max 25 caracters.', max_length=25, verbose_name='Nom de famille client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(help_text='Each customer has a mobile phone number with max 20             caracters.', max_length=20, verbose_name='Téléphone mobile client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Each customer has a phone number with max 20 caracters.', max_length=20, verbose_name='Téléphone fixe client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_customuser',
            field=models.ForeignKey(help_text='The admin team asign a salesperson to each customer.            this seller negotiates with the customer for contracts sign', on_delete=django.db.models.deletion.CASCADE, related_name='custumers', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='event creation datetime is automatically filled in.', verbose_name='Date création évènement')),
                ('datetime_updated', models.DateTimeField(auto_now=True, help_text='event update datetime is automatically filled in.', verbose_name='Date mise à jour évènement')),
                ('attendees', models.IntegerField(blank=True, help_text='number of attendees. Must be positive integer', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre convives')),
                ('event_date', models.DateField(blank=True, help_text='Date event. Format: AAAA-MM-JJ', verbose_name="Date de l'évènement")),
                ('notes', models.TextField(blank=True, help_text='Notes and organisation details.', verbose_name="Notes et détails d'organisation")),
                ('customer', models.ForeignKey(help_text='Each event is related to a custumer', on_delete=django.db.models.deletion.CASCADE, related_name='events_customer', to='CRM.customer', verbose_name='customer')),
                ('event_status', models.ForeignKey(help_text="Each event has a status: '1: En préparation',            '2: En cours' or '3: Terminé'", on_delete=django.db.models.deletion.CASCADE, related_name='events', to='CRM.eventstatus', verbose_name='status évènement')),
                ('support_customuser', models.ForeignKey(help_text='The admin team asign a support person to each customer.            this supprt personn manage event oàrganisation with the customer', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Contact support')),
            ],
        ),
    ]
