# Generated by Django 3.2.8 on 2021-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20211031_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['customer', '-datetime_created'], 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_status', 'event_date'], 'verbose_name_plural': 'Evènements'},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name_plural': 'Status évènements'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date event. Format: AAAA-MM-JJ', null=True, verbose_name="Date de l'évènement"),
        ),
    ]
