# Generated by Django 3.2.8 on 2021-10-31 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0008_auto_20211031_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(default='1', help_text="Each event has a status: '1: En préparation',            '2: En cours' or '3: Terminé'", on_delete=django.db.models.deletion.CASCADE, related_name='events', to='CRM.eventstatus', verbose_name='status évènement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_customuser',
            field=models.ForeignKey(blank=True, help_text='The admin team asign a support person to each customer.            this supprt personn manage event oàrganisation with the customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Contact support'),
        ),
    ]
