# Generated by Django 3.2.8 on 2021-10-31 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_auto_20211031_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True, help_text='number of attendees. Must be positive integer', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre convives'),
        ),
    ]
