# Generated by Django 3.2.8 on 2021-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(help_text='For event status choice. Three choices            possibles: En préparation, En cours, Terminé', max_length=250, verbose_name='Status évènement'),
        ),
    ]
