# Generated by Django 3.2.9 on 2021-11-03 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0012_alter_contract_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales_customuser',
            field=models.ForeignKey(blank=True, help_text='The admin team asign a salesperson to each customer.            this seller negotiates with the customer for contracts sign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumers', to=settings.AUTH_USER_MODEL, verbose_name='Contact vendeur'),
        ),
    ]
