# Generated by Django 3.2.9 on 2021-11-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_auto_20211104_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(blank=True, help_text="Each event has a status: '1: En préparation',            '2: En cours' or '3: Terminé'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_eventstatus', to='CRM.eventstatus', verbose_name='status évènement'),
        ),
    ]
