# Generated by Django 3.2.9 on 2021-11-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_alter_event_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
    ]
